### ISSUE TITLE
Material that is used in a course but is not teaching material

### ISSUE THREAD

**Issue by philbarker** [open-curriculum/oerschema#32]
[SupportingMaterial](http://oerschema.org/SupportingMaterial/) is "Material that teaches the learning objectives of the course" but what about material that is used in a course or provides information about it, but doesn't explicitly teach anything?

In OCX we defined:
- [SupplementalMaterial](https://k12ocx.github.io/k12ocx-specs/inpage/supplementalmaterial/): "Material associated with an instructional component that provides additional information about that component." examples include Curriculum guides, Family course guides Student study guides.
- [ReferencedMaterial](https://k12ocx.github.io/k12ocx-specs/inpage/referencedmaterial/): "Material associated with an instructional component that is referenced by that component." Examples include primary sources analysed in activities or assessments, material studied in Courses, raw material used in activities or assessments. (so if an Eng Lit unit is about Jane Eyre, the recommended text of Jane Eyre would be ReferencedMaterial)

We lumped Referenced, Supplemental and Supporting material together as AssociatedMaterial

**Comment by kat-wehr** [comment]
I like this specificity - we argued for a while about what to do about "SupportingMaterial" at all. Mike may have more to say about it though.

**Comment by philbarker** [comment]
Cool. Interested in what Mike has to say. In the meantime I'll have a go at adding these.

**Comment by michael-collins** [comment]
These are good additions, I'm for adding them to the schema.

**Comment by michael-collins** [comment]
Re-opening until Alex get's the urls working. They are updated in the schema list, but the pages aren't generating.
