### ISSUE TITLE
Local development install doesn't work for me (Ubuntu)

### ISSUE THREAD

**Issue by philbarker** [open-curriculum/oerschema#35]
On Linux 4.15.0-47-generic #50-Ubuntu SMP x86_64 GNU/Linux with npm 3.5.2 `$ npm install` gives error messages, see [errorMsgs.txt](https://github.com/open-curriculum/oerschema/files/3121551/errorMsgs.txt)
Also attached [npm-debug.log](https://github.com/open-curriculum/oerschema/files/3121557/npm-debug.log)

**Comment by curiosity26** [comment]
This is most likely related to #38 and should be fixed along with it

**Comment by michael-collins** [comment]
@philbarker Go ahead and have a look at the updated readme file to get this up and running locally. I just tested on my machine, and it was fairly easy once I updated my gulp install.

**Comment by philbarker** [comment]
It works (I think)
`$ npm ci` just gives a message about the usage of `npm <command>` with no `ci` listed in the commands. Is there an undocumented version of dependency requirement?
You could be kind to us non-node users and remind us in the README that `$ npm install` needs to be run at some point --never underestimate what it takes to make something idiot proof ;)
Thank you.

**Comment by curiosity26** [comment]
Phil, you will need to be using the latest version of node and npm.

The `ci` feature was added to npm in version 5. It's the same as `install`
but it reads from the lock file and doesn't update dependencies.

Thanks
