### ISSUE TITLE
Transfer project to elmsln organization

### ISSUE THREAD

**Issue by btopro** [open-curriculum/oerschema#44]
We're doing house keeping and getting all our projects in alignment marketing wise. Let's get this moved there so we can unify issues related to the project, increase visibility for the org and for this important project.

**Comment by michael-collins** [comment]
We are still actively developing things, so this isn't good timing to think about moving it to another repository.

**Comment by btopro** [comment]
I'm not sure your following how minor this is. You transfer the repo, the entire thing just shows up at a different address and the old one redirects to the new. Anyone going to https://github.com/open-curriculum/oerschema would redirect the user to https://github.com/elmsln/oerschema . Issue queue and everything else comes over; literally just helps get it all in one brand so it's easier for us to promote in one place.
